# Generated by Django 4.1 on 2022-09-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categories_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name': 'Category list', 'verbose_name_plural': 'Category list'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['title'], 'verbose_name': 'Product list', 'verbose_name_plural': 'Product list'},
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create time'),
        ),
        migrations.AlterField(
            model_name='products',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
    ]
